// Server-side helpers for the client portal — the emails it sends, and the
// magic-link minting behind them. Underscore prefix = not an API route.
//
// The sign-in link is generated by Supabase's Auth admin API and then delivered
// through OUR sender, so a customer's first login looks like 6Homes rather than
// a bare Supabase notification. It also means the link goes through the same
// safe-mode guard as every other email: while safe mode is on, login links land
// in the test inbox, which is what stops a customer signing in before launch.
import {
  brandFrame, bKicker, bH1, bP, bBtn, bPanel, bSmall, bDivider, esc, escLines, COMPANY,
} from './_brand.js'
import { sendEmail } from './_email.js'
import { BUILD_STAGES, stageById, stageIndex } from '../src/lib/projectStages.js'
import { docStatusMeta } from '../src/lib/portal.js'

const PORTAL_URL = (process.env.PORTAL_URL || process.env.ADMIN_URL || 'https://portal.6homes.com').replace(/\/+$/, '')

export const portalLink = (path = '/portal') => `${PORTAL_URL}${path}`

/**
 * Mint a one-click sign-in link for a customer.
 *
 * `generateLink` only works for a user that exists, so an address we've never
 * seen is created first — confirmed, with no password, because the only way
 * into this account is a link we email. Creating the user here rather than
 * letting the client sign themselves up is what keeps the portal closed: an
 * address gets an account only once an admin has attached it to a build.
 */
export async function magicLink(sb, email, redirectPath = '/portal') {
  const redirectTo = portalLink(redirectPath)

  const attempt = async () =>
    sb.auth.admin.generateLink({ type: 'magiclink', email, options: { redirectTo } })

  let { data, error } = await attempt()

  // "User not found" is the expected first-invite case, not a failure.
  if (error) {
    const { error: createError } = await sb.auth.admin.createUser({
      email,
      email_confirm: true,
      user_metadata: { portal: true },
    })
    // A racing invite may have created it between the two calls; retry either way.
    if (createError && !/already/i.test(createError.message)) {
      throw new Error(`Could not create a portal login for ${email}: ${createError.message}`)
    }
    ;({ data, error } = await attempt())
  }

  if (error) throw new Error(`Could not generate a sign-in link: ${error.message}`)

  const link = data?.properties?.action_link
  if (!link) throw new Error('Supabase returned no sign-in link.')
  return link
}

// ── Shared email furniture ──────────────────────────────────────────────────

// The same six-segment rail the stage-update emails use and the portal draws on
// screen. Repeating one device across inbox and portal is what makes them read
// as the same object rather than two systems talking about the same build.
function progressRail(currentIndex) {
  const cells = BUILD_STAGES.map((s, i) => {
    const done = i <= currentIndex
    return `<td style="padding:0 2px;width:${Math.floor(100 / BUILD_STAGES.length)}%">
      <div style="height:5px;border-radius:3px;background:${done ? '#0D7982' : '#DFE6E9'}"></div>
      <div style="margin-top:7px;font-family:Helvetica,Arial,sans-serif;font-size:9px;line-height:1.3;letter-spacing:.04em;color:${i === currentIndex ? '#0E5476' : '#64757E'};${i === currentIndex ? 'font-weight:600;' : ''}text-transform:uppercase">${s.name}</div>
    </td>`
  }).join('')
  return `<table style="width:100%;border-collapse:collapse;margin:0 0 26px"><tr>${cells}</tr></table>`
}

function docList(items = []) {
  if (!items.length) return ''
  const rows = items.map((d) => `
    <tr>
      <td style="padding:9px 0;border-bottom:1px solid #DFE6E9;font-family:Helvetica,Arial,sans-serif;font-size:13px;line-height:1.5;color:#16242C">
        <strong style="color:#0E5476">${esc(d.label)}</strong>
        ${d.required === false ? '<span style="color:#64757E;font-size:11px"> · if you have it</span>' : ''}
        ${d.note ? `<div style="margin-top:3px;font-size:12px;color:#64757E">${escLines(d.note)}</div>` : ''}
      </td>
    </tr>`).join('')
  return `<table style="width:100%;border-collapse:collapse;margin:0 0 24px">${rows}</table>`
}

const firstNameOf = (name) => (String(name || '').split(' ')[0] || 'there')

// ── Customer-facing emails ──────────────────────────────────────────────────

/**
 * First invitation. Explains what the portal is for before asking them to click
 * anything — an unexplained login link from a builder reads like phishing.
 */
export function renderPortalInvite({ project, customer, link, pending = [], settings }) {
  const stage = stageById(project?.stage)
  const inner =
    bKicker('Your build, online') +
    bH1('Track your home from here') +
    bP(`Hi ${esc(firstNameOf(customer?.name))},`) +
    bP(
      `We've set up a private page for ${esc(project?.name || 'your build')}. It shows which stage your home is at, ` +
      'holds every document we\'ve issued you, and is where you send us the paperwork we need.'
    ) +
    (stage ? progressRail(stageIndex(project.stage)) : '') +
    (pending.length
      ? bP('<strong style="color:#0E5476">To get started, we need these from you:</strong>') + docList(pending)
      : '') +
    bBtn('Open your build', link) +
    bSmall(
      'This link signs you in and works once. Ask for a new one from the portal any time — there\'s no password to remember. ' +
      `If you weren't expecting this, ignore it and call us on <a href="${COMPANY.phoneHref}" style="color:#64757E">${COMPANY.phone}</a>.`
    )

  return {
    subject: `Your 6Homes build is online — ${project?.name || 'view your progress'}`,
    html: brandFrame(inner, { footerLabel: 'Your Build', preheader: 'A private page for your build: progress, documents and approvals.' }),
  }
}

/** Returning sign-in. Deliberately terse — they asked for it seconds ago. */
export function renderPortalLogin({ link, email }) {
  const inner =
    bKicker('Sign in') +
    bH1('Here\'s your link') +
    bP(`Click below to open your build. The link expires in an hour and works once.`) +
    bBtn('Open your build', link) +
    bSmall(
      `Requested for ${esc(email)}. If that wasn't you, nothing has happened — the link only works from this email, ` +
      'and you can safely ignore it.'
    )
  return {
    subject: 'Your 6Homes sign-in link',
    html: brandFrame(inner, { footerLabel: 'Sign In', preheader: 'Your one-time link to open your build.' }),
  }
}

/** "We need these from you" — sent when an admin adds document requests. */
export function renderDocsRequested({ project, customer, items, link }) {
  const inner =
    bKicker('Action needed') +
    bH1(items.length === 1 ? 'One document to send us' : `${items.length} documents to send us`) +
    bP(`Hi ${esc(firstNameOf(customer?.name))},`) +
    bP(`To keep ${esc(project?.name || 'your build')} moving we need the following. You can upload them straight to your build page — no need to email them.`) +
    docList(items) +
    bBtn('Upload them now', link) +
    bSmall('Anything you can\'t find, tell us on your build page and we\'ll help you track it down.')

  return {
    subject: `${items.length === 1 ? 'A document' : `${items.length} documents`} we need for ${project?.name || 'your build'}`,
    html: brandFrame(inner, { footerLabel: 'Your Build', preheader: 'Upload them from your build page.' }),
  }
}

/** A reply from the project team, landing in their inbox. */
export function renderPortalReply({ project, customer, body, author, link }) {
  const inner =
    bKicker('Your project team') +
    bH1('A message about your build') +
    bP(`Hi ${esc(firstNameOf(customer?.name))},`) +
    bPanel(`<div style="font-family:Helvetica,Arial,sans-serif;font-size:14px;line-height:1.7;color:#39474F">${escLines(body)}</div>`) +
    bP(`— ${esc(author || '6Homes')}`) +
    bBtn('Reply on your build page', `${link}#messages`)
  return {
    subject: `Re: ${project?.name || 'your 6Homes build'}`,
    html: brandFrame(inner, { footerLabel: 'Your Build', preheader: String(body).slice(0, 120) }),
  }
}

// ── Team notifications ──────────────────────────────────────────────────────
// Plain and scannable. These are read on a phone between site visits, so the
// subject line has to carry the whole event on its own.

export function renderTeamUpload({ project, email, request, files, adminUrl }) {
  const inner =
    bKicker('Portal upload') +
    bH1(esc(request?.label || 'A document arrived')) +
    bP(`<strong>${esc(email)}</strong> uploaded ${files.length === 1 ? 'a file' : `${files.length} files`} against <strong>${esc(project?.name || project?.id)}</strong>.`) +
    bPanel(`<div style="font-family:Helvetica,Arial,sans-serif;font-size:13px;line-height:1.8;color:#39474F">${files.map((f) => esc(f.name)).join('<br />')}</div>`) +
    bBtn('Review it in the CRM', `${adminUrl}/projects/${project?.id}`)
  return {
    subject: `[Portal] ${request?.label || 'Upload'} — ${project?.name || project?.id}`,
    html: brandFrame(inner, { footerLabel: 'CRM', preheader: `${email} uploaded ${files.length} file(s).` }),
  }
}

export function renderTeamApproval({ project, email, approval, adminUrl }) {
  const inner =
    bKicker('Portal approval') +
    bH1(esc(approval?.label || 'Approved')) +
    bP(`<strong>${esc(email)}</strong> approved <strong>${esc(approval?.label || '')}</strong> on <strong>${esc(project?.name || project?.id)}</strong>.`) +
    bDivider() +
    bP(esc(approval?.body || '')) +
    bBtn('Open the build', `${adminUrl}/projects/${project?.id}`)
  return {
    subject: `[Portal] Approved: ${approval?.label || ''} — ${project?.name || project?.id}`,
    html: brandFrame(inner, { footerLabel: 'CRM', preheader: `${email} approved ${approval?.label || ''}.` }),
  }
}

export function renderTeamMessage({ project, email, body, adminUrl }) {
  const inner =
    bKicker('Portal message') +
    bH1('A customer wrote in') +
    bP(`<strong>${esc(email)}</strong> on <strong>${esc(project?.name || project?.id)}</strong>:`) +
    bPanel(`<div style="font-family:Helvetica,Arial,sans-serif;font-size:14px;line-height:1.7;color:#39474F">${escLines(body)}</div>`) +
    bBtn('Reply from the CRM', `${adminUrl}/projects/${project?.id}#portal`)
  return {
    subject: `[Portal] Message — ${project?.name || project?.id}`,
    html: brandFrame(inner, { footerLabel: 'CRM', preheader: String(body).slice(0, 120) }),
  }
}

/** Every portal send goes through here so it lands in the email log tagged. */
export async function sendPortal({ to, subject, html, projectId, customerId, emailType, settings }) {
  return sendEmail({
    to,
    subject,
    html,
    replyTo: settings?.emails?.replyTo,
    projectId,
    customerId,
    emailType,
  })
}

export { docStatusMeta }
